on :
  push :
    branches :
      - development
jobs:
  job_number_one:
    runs-on : ubuntou-latest
    steps : 
      - name : checkout Code
        uses : actions/checkout@v5
      - name : restore dotnet
        uses : actions/setup-dotnet@v5
        with :
          dotnet-version : '9.0.x'
      - name : restore packages
        run : dotnet restore
      - name : build application
        run : dotnet build --no-restore
